# ==============================================================================
# AGSoft_Crop_Face.py
# ==============================================================================
# Нода: 🧑✂️AGSoft Crop Face
#
# ОСОБЕННОСТИ:
# Обнаруживает лица на изображениях с помощью RetinaFace и кадрирует их с настраиваемыми параметрами.
# Поддерживает пакетную обработку, фильтрацию по маске, пресеты соотношения сторон и независимый сдвиг по горизонтали и вертикали.
# Выводит кадрированные лица и данные об их bounding box
#
# Автор: AGSoft
# Дата: 16.07.2026
# ==============================================================================
import torch
import numpy as np
from typing import Tuple, List, Dict, Any, Optional
import comfy.utils
from comfy.model_management import get_torch_device
import os
import sys
import cv2

NODE_DIR = os.path.dirname(os.path.abspath(__file__))
RF_DIR = os.path.join(NODE_DIR, "Pytorch_Retinaface")
RETINAFACE_AVAILABLE = False
Pytorch_RetinaFace = None

if os.path.exists(RF_DIR) and os.path.isdir(RF_DIR):
    init_file = os.path.join(RF_DIR, "__init__.py")
    if not os.path.exists(init_file):
        try:
            with open(init_file, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by AGSoft to fix relative imports\n")
        except Exception as e:
            print(f"[AGSoft] ⚠️ Не удалось создать __init__.py: {e}")
            
    if NODE_DIR not in sys.path:
        sys.path.insert(0, NODE_DIR)
        
    try:
        import Pytorch_Retinaface.pytorch_retinaface as rf_module
        Pytorch_RetinaFace = rf_module.Pytorch_RetinaFace
        RETINAFACE_AVAILABLE = True
        print("[AGSoft] ✅ RetinaFace успешно загружен как пакет!")
    except Exception as e:
        print(f"[AGSoft] ❌ Ошибка загрузки RetinaFace: {e}")
        import traceback
        traceback.print_exc()
else:
    print(f"[AGSoft] ❌ Папка 'Pytorch_Retinaface' не найдена по пути: {RF_DIR}")

class AGSoftCropFace:
    """
    AGSoft Crop Face - Высокоточное обнаружение и кадрирование лиц через RetinaFace.
    """
    DESCRIPTION = (
         "EN: Detects faces in images using RetinaFace and crops them with customizable parameters. "
         "Supports batch processing, mask-based filtering, aspect ratio presets, and independent horizontal/vertical shift. "
         "Outputs cropped faces and their bounding box data.\n\n"
         "RU: Обнаруживает лица на изображениях с помощью RetinaFace и кадрирует их с настраиваемыми параметрами. "
         "Поддерживает пакетную обработку, фильтрацию по маске, пресеты соотношения сторон и независимый сдвиг по горизонтали/вертикали. "
         "Выводит кадрированные лица и данные об их bounding box."
    )

    def __init__(self):
        self.face_detector = None
        self.current_max_faces = None

    @classmethod
    def INPUT_TYPES(s) -> Dict[str, Dict[str, Any]]:
        return {
            "required": {
                "image": (
                    "IMAGE",
                    {
                        "tooltip": 
                        "EN:  Input image containing one or more faces to detect and crop.\n"
                        "    Supports batch processing (multiple images at once).\n\n"
                        "RU: 📷 Входное изображение, содержащее одно или несколько лиц для обнаружения и кадрирования.\n"
                        "    Поддерживает пакетную обработку (несколько изображений сразу)."
                    }
                ),
                "number_of_faces": (
                    "INT",
                    {
                        "default": 5,
                        "min": 1,
                        "max": 100,
                        "step": 1,
                        "display": "number",
                        "tooltip":
                        "EN: 🔢 How many faces to return. Faces are sorted by size (largest first).\n"
                        "    • If more faces found → returns only this number (largest ones)\n"
                        "    • If fewer faces found → returns all found (no duplicates)\n\n"
                        "RU:  Сколько лиц вернуть. Лица сортируются по размеру (большие первыми).\n"
                        "    • Если найдено больше → вернет только указанное количество (самые большие)\n"
                        "    • Если найдено меньше → вернет все найденные (без дубликатов)"
                    }
                ),
                "scale_factor": (
                    "FLOAT",
                    {
                        "default": 2.0,
                        "min": 1.0,
                        "max": 5.0,
                        "step": 0.1,
                        "tooltip":
                        "EN:  How much to enlarge the crop around the face.\n"
                        "    • 1.0 = Tight crop (face fills almost entire image)\n"
                        "    • 2.0 = Comfortable crop (face + some background, recommended)\n"
                        "    • 3.0+ = Wide crop (face + lots of surrounding context)\n\n"
                        "RU: 📏 Насколько увеличить область кадрирования вокруг лица.\n"
                        "    • 1.0 = Плотный кроп (лицо занимает почти всё изображение)\n"
                        "    • 2.0 = Комфортный кроп (лицо + немного фона, рекомендуется)\n"
                        "    • 3.0+ = Широкий кроп (лицо + много окружающего контекста)"
                    }
                ),
                "shift_factor_x": (
                    "FLOAT",
                    {
                        "default": 0.50,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip":
                        "EN: ↔️ Horizontal position of the face within the cropped image.\n"
                        "    Controls where the face sits horizontally in the final crop.\n\n"
                        "    • 0.00 = Face at the far LEFT (more space on right)\n"
                        "    • 0.50 = Face in the CENTER (balanced, default)\n"
                        "    • 1.00 = Face at the far RIGHT (more space on left)\n\n"
                        "RU: ↔️ Горизонтальная позиция лица в кадрированном изображении.\n"
                        "    Контролирует, где лицо располагается по горизонтали в финальном кадре.\n\n"
                        "    • 0.00 = Лицо слева (больше места справа)\n"
                        "    • 0.50 = Лицо в ЦЕНТРЕ (сбалансировано, по умолчанию)\n"
                        "    • 1.00 = Лицо справа (больше места слева)"
                    }
                ),
                "shift_factor_y": (
                    "FLOAT",
                    {
                        "default": 0.50,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip":
                        "EN: ⬆️⬇️ Vertical position of the face within the cropped image.\n"
                        "    Controls where the face sits vertically in the final crop.\n\n"
                        "    • 0.00 = Face at the very TOP (more space below)\n"
                        "    • 0.50 = Face in the CENTER (balanced, default)\n"
                        "    • 1.00 = Face at the very BOTTOM (more space above)\n\n"
                        "RU: ⬆️⬇️ Вертикальная позиция лица в кадрированном изображении.\n"
                        "    Контролирует, где лицо располагается по вертикали в финальном кадре.\n\n"
                        "    • 0.00 = Лицо в самом ВЕРХУ (больше места снизу)\n"
                        "    • 0.50 = Лицо в ЦЕНТРЕ (сбалансировано, по умолчанию)\n"
                        "    • 1.00 = Лицо в самом НИЗУ (больше места сверху)"
                    }
                ),
                "start_index": (
                    "INT",
                    {
                        "default": 0,
                        "min": 0,
                        "max": 999,
                        "step": 1,
                        "display": "number",
                        "tooltip":
                        "EN: 🔀 Which face to start from. Faces sorted by size (0=largest, 1=2nd, etc.)\n"
                        "    • Index 0 = Start from largest face (main subject)\n"
                        "    • Index 1 = Skip largest, start from 2nd largest\n"
                        "    Selection wraps cyclically if more faces requested than found.\n\n"
                        "RU: 🔀 С какого лица начать. Лица отсортированы по размеру (0=самое большое, 1=2-е и т.д.)\n"
                        "    • Индекс 0 = Начать с самого большого лица (главный объект)\n"
                        "    • Индекс 1 = Пропустить самое большое, начать со 2-го\n"
                        "    Выбор циклический, если запрошено больше лиц, чем найдено."
                    }
                ),
                "max_faces_per_image": (
                    "INT",
                    {
                        "default": 50,
                        "min": 1,
                        "max": 1000,
                        "step": 1,
                        "tooltip":
                        "EN: 🔍 Maximum faces detector will look for (safety limit).\n"
                        "    Different from 'number_of_faces':\n"
                        "    • max_faces_per_image = How many to DETECT (technical limit)\n"
                        "    • number_of_faces = How many to RETURN (your choice)\n\n"
                        "RU: 🔍 Максимум лиц, которые детектор будет искать (предел безопасности).\n"
                        "    Отличается от 'number_of_faces':\n"
                        "    • max_faces_per_image = Сколько ОБНАРУЖИТЬ (технический лимит)\n"
                        "    • number_of_faces = Сколько ВЕРНУТЬ (ваш выбор)"
                    }
                ),
                "aspect_ratio": (
                    ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "5:4", "4:5"],
                    {
                        "default": "1:1",
                        "tooltip":
                        "EN: 📐 Width-to-height ratio of the final crop.\n"
                        "    • 1:1 = Square (Instagram, avatars, face swaps)\n"
                        "    • 3:4 = Portrait (classic portrait orientation)\n"
                        "    • 16:9 = Widescreen (YouTube/video format)\n"
                        "    • 9:16 = Vertical (TikTok/Reels/Stories)\n\n"
                        "RU: 📐 Соотношение ширины к высоте финального кропа.\n"
                        "    • 1:1 = Квадрат (Instagram, аватарки, замена лиц)\n"
                        "    • 3:4 = Портрет (классическая портретная ориентация)\n"
                        "    • 16:9 = Широкоформатный (YouTube/видео)\n"
                        "    • 9:16 = Вертикальный (TikTok/Reels/Stories)"
                    }
                ),
                "confidence_threshold": (
                    "FLOAT",
                    {
                        "default": 0.7,
                        "min": 0.1,
                        "max": 1.0,
                        "step": 0.05,
                        "tooltip":
                        "EN: 🎯 Minimum confidence to accept a detected face (0.0-1.0).\n"
                        "    • 0.90-1.0 = Very strict (only 100% certain faces)\n"
                        "    • 0.70-0.85 = Balanced (recommended default)\n"
                        "    • 0.50-0.65 = Lenient (more faces, possible false positives)\n\n"
                        "RU: 🎯 Минимальная уверенность для принятия обнаруженного лица (0.0-1.0).\n"
                        "    • 0.90-1.0 = Очень строго (только 100% уверенные лица)\n"
                        "    • 0.70-0.85 = Сбалансировано (рекомендуется по умолчанию)\n"
                        "    • 0.50-0.65 = Мягко (больше лиц, возможны ложные срабатывания)"
                    }
                ),
                "divisible_by": (
                    "INT",
                    {
                        "default": 8,
                        "min": 1,
                        "max": 64,
                        "step": 1,
                        "display": "number",
                        "tooltip":
                        "EN: 🔢 Round output dimensions to multiples of N.\n"
                        "    Important for VAE/KSampler compatibility (they need dims divisible by 8/16/32).\n"
                        "    • 8 = Standard (works with most nodes, recommended)\n"
                        "    • 16 = Stricter (some VAE models)\n"
                        "    • 1 = No rounding (use only if you know why)\n\n"
                        "RU: 🔢 Округлить размеры выхода до кратных N.\n"
                        "    Важно для совместимости с VAE/KSampler (требуют размеры кратные 8/16/32).\n"
                        "    • 8 = Стандарт (работает с большинством нод, рекомендуется)\n"
                        "    • 16 = Строже (некоторые модели VAE)\n"
                        "    • 1 = Без округления (используйте только если знаете зачем)"
                    }
                ),
            },
            "optional": {
                "mask": (
                    "MASK",
                    {
                        "tooltip":
                        "EN: 🎭 Optional mask to limit where faces are detected.\n"
                        "    Only faces whose CENTER is in WHITE (bright) areas will be detected.\n"
                        "    • White (1.0) = Detector searches here\n"
                        "    • Black (0.0) = Detector ignores this area\n\n"
                        "RU: 🎭 Опциональная маска для ограничения области поиска лиц.\n"
                        "    Будут обнаружены только лица, чей ЦЕНТР в БЕЛЫХ (ярких) областях.\n"
                        "    • Белый (1.0) = Детектор ищет здесь\n"
                        "    • Черный (0.0) = Детектор игнорирует эту область"
                    }
                ),
            },
        }

    RETURN_TYPES = ("IMAGE", "CROP_DATA")
    RETURN_NAMES = ("face", "crop_data")
    FUNCTION = "crop_face"
    CATEGORY = "AGSoft/Crop"

    def crop_face(
        self, image: torch.Tensor, number_of_faces: int,
        scale_factor: float, shift_factor_x: float, shift_factor_y: float, start_index: int,
        max_faces_per_image: int, aspect_ratio: str, confidence_threshold: float = 0.7,
        divisible_by: int = 8, mask: Optional[torch.Tensor] = None
    ) -> Tuple[torch.Tensor, List[Tuple[int, int, int, int]]]:
        
        if not RETINAFACE_AVAILABLE:
            raise ImportError("Модуль Pytorch_RetinaFace не загружен.")
            
        try:
            if (self.face_detector is None or 
                self.current_max_faces != max_faces_per_image):
                
                print(f"[AGSoft] Загрузка RetinaFace (MobileNet0.25, max_faces={max_faces_per_image})...")
                self.face_detector = Pytorch_RetinaFace(
                    top_k=50,
                    keep_top_k=max_faces_per_image,
                    device=str(get_torch_device())
                )
                self.current_max_faces = max_faces_per_image
                print("[AGSoft] ✅ RetinaFace инициализирована")

            aspect_ratio_float = self._parse_aspect_ratio(aspect_ratio)
            batch_size = image.shape[0]
            all_cropped_faces = []
            all_crop_data = []
            all_base_sizes = []
            
            print(f"[AGSoft] Обработка {batch_size} изображения(й)")
            
            mask_np = None
            if mask is not None:
                print("[AGSoft] ✅ Маска подключена")
                mask_np = mask[0].cpu().numpy() if len(mask.shape) == 3 else mask.cpu().numpy()

            for img_idx in range(batch_size):
                single_image = image[img_idx]
                img_np = (single_image.cpu().numpy() * 255.0).astype(np.float32)
                
                if img_np.shape[2] == 4:
                    img_np = img_np[:, :, :3]
                    
                img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
                detections = self.face_detector.detect_faces(img_np)
                
                if detections is None or len(detections) == 0:
                    print(f"[AGSoft]   Изображение {img_idx}: лиц не обнаружено")
                    continue
                    
                print(f"[AGSoft]   Изображение {img_idx}: обнаружено {len(detections)} лиц(а)")
                
                valid_detections = []
                for det in detections:
                    x1, y1, x2, y2 = det[:4]
                    confidence = det[4] if len(det) > 4 else 1.0
                    
                    if confidence >= confidence_threshold:
                        if mask_np is not None:
                            cx_check = int((x1 + x2) / 2)
                            cy_check = int((y1 + y2) / 2)
                            mask_h, mask_w = mask_np.shape
                            cx_check = max(0, min(cx_check, mask_w - 1))
                            cy_check = max(0, min(cy_check, mask_h - 1))
                            
                            if mask_np[cy_check, cx_check] < 0.5:
                                continue
                                
                        w, h = x2 - x1, y2 - y1
                        size = w * h
                        valid_detections.append((x1, y1, x2, y2, confidence, size))
                        
                if len(valid_detections) == 0:
                    print(f"[AGSoft]   Лиц с достаточной уверенностью не найдено")
                    continue
                    
                valid_detections.sort(key=lambda x: x[5], reverse=True)
                print(f"[AGSoft]   Найдено {len(valid_detections)} валидных лиц")
                
                total_faces = len(valid_detections)
                actual_number = min(number_of_faces, total_faces)
                
                if actual_number < number_of_faces:
                    print(f"[AGSoft]   ⚠️ Запрошено {number_of_faces}, но найдено {total_faces}. Возвращаем {actual_number}")
                    
                selected_detections = []
                for i in range(actual_number):
                    idx = (start_index + i) % total_faces
                    selected_detections.append(valid_detections[idx])
                    
                print(f"[AGSoft]   Выбрано {len(selected_detections)} лиц(а) начиная с индекса {start_index}")
                
                for i, (x1, y1, x2, y2, conf, size) in enumerate(selected_detections):
                    x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
                    w, h = x2 - x1, y2 - y1
                    
                    print(f"[AGSoft]     Лицо {i+1}: bbox=[{x1},{y1},{w}x{h}], conf={conf:.2f}")
                    
                    cx = x1 + w / 2
                    cy = y1 + h / 2
                    base_size = max(w, h) * scale_factor
                    all_base_sizes.append(base_size)
                    
                    if aspect_ratio_float > 1.0:
                        crop_w = int(base_size * aspect_ratio_float)
                        crop_h = int(base_size)
                    elif aspect_ratio_float < 1.0:
                        crop_w = int(base_size)
                        crop_h = int(base_size / aspect_ratio_float)
                    else:
                        crop_w = int(base_size)
                        crop_h = int(base_size)
                        
                    # Округление размеров до кратных divisible_by
                    if divisible_by > 1:
                        crop_w = (crop_w // divisible_by) * divisible_by
                        crop_h = (crop_h // divisible_by) * divisible_by
                        crop_w = max(1, crop_w)
                        crop_h = max(1, crop_h)
                        
                    # === НОВОЕ: Сдвиг по горизонтали и вертикали ===
                    # shift_factor_x: 0.0=лево, 0.5=центр, 1.0=право
                    # shift_factor_y: 0.0=верх, 0.5=центр, 1.0=низ
                    cx_shifted = cx - (crop_w * (shift_factor_x - 0.5))
                    cy_shifted = cy - (crop_h * (shift_factor_y - 0.5))
                    
                    nx1 = int(cx_shifted - crop_w / 2)
                    nx2 = int(cx_shifted + crop_w / 2)
                    ny1 = int(cy_shifted - crop_h / 2)
                    ny2 = int(cy_shifted + crop_h / 2)
                    
                    img_h, img_w = img_np.shape[:2]
                    nx1 = max(0, nx1)
                    ny1 = max(0, ny1)
                    nx2 = min(img_w, nx2)
                    ny2 = min(img_h, ny2)
                    
                    cropped = single_image[ny1:ny2, nx1:nx2]
                    
                    if cropped.numel() > 0:
                        all_cropped_faces.append(cropped)
                        all_crop_data.append((nx1, ny1, nx2 - nx1, ny2 - ny1))
                        print(f"[AGSoft]       Кадрировано: [{nx1}:{nx2}, {ny1}:{ny2}]")
                        
            if not all_cropped_faces:
                print("[AGSoft] ⚠️ Лица не обнаружены")
                return (image, [(0, 0, image.shape[2], image.shape[1])])
                
            print(f"[AGSoft] ✅ Всего кадрировано: {len(all_cropped_faces)} лиц(а)")
            
            # Вычисляем финальный размер на основе среднего base_size
            avg_base_size = sum(all_base_sizes) / len(all_base_sizes)
            
            # Вычисляем финальные размеры на основе aspect_ratio
            if aspect_ratio_float > 1.0:
                # Широкий формат (3:2, 5:4, 16:9)
                final_w = int(avg_base_size / aspect_ratio_float)
                final_h = int(avg_base_size)
            elif aspect_ratio_float < 1.0:
                # Высокий формат (2:3, 4:5, 9:16)
                final_w = int(avg_base_size)
                final_h = int(avg_base_size * aspect_ratio_float)
            else:
                # Квадрат 1:1
                final_w = int(avg_base_size)
                final_h = int(avg_base_size)
                
            # Округляем до кратных divisible_by
            if divisible_by > 1:
                final_w = (final_w // divisible_by) * divisible_by
                final_h = (final_h // divisible_by) * divisible_by
                final_w = max(1, final_w)
                final_h = max(1, final_h)
                
            print(f"[AGSoft] Финальный размер: {final_w}x{final_h} (aspect_ratio={aspect_ratio}, avg_base={avg_base_size:.0f})")
            
            # Приводим все лица к final_w x final_h
            resized = []
            for face in all_cropped_faces:
                if face.shape[0] != final_h or face.shape[1] != final_w:
                    face_resized = comfy.utils.common_upscale(
                        face.unsqueeze(0).movedim(-1, 1), final_h, final_w, "lanczos", "center"
                    ).movedim(1, -1).squeeze(0)
                    resized.append(face_resized)
                else:
                    resized.append(face)
                    
            return (torch.stack(resized, dim=0), all_crop_data)
            
        except Exception as e:
            print(f"❌ [AGSoft] Ошибка: {str(e)}")
            import traceback
            traceback.print_exc()
            return (image, [(0, 0, image.shape[2], image.shape[1])])

    def _parse_aspect_ratio(self, aspect_ratio_str: str) -> float:
        try:
            w, h = map(float, aspect_ratio_str.split(':'))
            return w / h
        except:
            return 1.0

NODE_CLASS_MAPPINGS = {"AGSoftCropFace": AGSoftCropFace}
NODE_DISPLAY_NAME_MAPPINGS = {"AGSoftCropFace": "🧑✂️AGSoft Crop Face"}